#!/bin/bash
/usr/bin/socat -d -d "tcp4-listen:"$2",reuseaddr,fork" "tcp-connect:"$1":"$2 2>&1 |while read curline;do 
											echo $curline|grep "accepting connection from" -q && ( ip=$(echo "$curline"|cut -d"=" -f2-|cut -d" " -f2-|cut -d: -f1) ; (echo "Subject: "$(hostname)" LEGACY SQL CONNECTION FROM "$ip ; echo "SQL CONNECTION INCOMING";echo "##########";echo "SOURCE:$ip";echo -n "DATE:";date -u +%Y-%m-%d_%H:%M:%S" "UTC;echo "########HOST INFOS:#########";host $ip 2>&1 ;echo   ;whois -h whois.cymru.com " -v $ip" 2>&1;echo "########## " )  |sendmail  root  )  ;done
